name: Run and Report Tests

on:
  pull_request:
    branches:
      - dev
      - main

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Run Tests
        run: dotnet test src --logger "trx;LogFileName=test-results.trx"

      - name: Report Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: .NET Test Report
          path: '**/test-results.trx'
          reporter: dotnet-trx
